name: decision_aide_frontend
description: Application Flutter d'aide à la décision pédagogique
publish_to: 'none'
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

